name: users_app_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  freezed_annotation: ^2.4.4
  rxdart: ^0.28.0
  json_serializable: ^6.2.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true
